site_name: Changes That Heal
site_url: https://dgrothman.github.io/changesthatheal
site_description: A site about mental health and using the 5 core symptoms to help develop a framework for handling life.

nav:
  - Home: 'index.md'
  - Class 1: '/C1-SafePeople/index.md'
  - Class 2: '/C2-Reality/index.md'

theme:
    name: material

# Extensions
markdown_extensions:
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 
